version: "2"

run:
  modules-download-mode: readonly
  tests: true

linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - nolintlint
    - revive

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
